import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    initial=True
    dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.CreateModel(name="Company",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("name",models.CharField(max_length=200)),("country",models.CharField(default="ID",max_length=2)),("currency",models.CharField(default="IDR",max_length=3)),("npwp",models.CharField(blank=True,max_length=40)),("address",models.TextField(blank=True)),("email",models.EmailField(blank=True,max_length=254)),("phone",models.CharField(blank=True,max_length=40)),("bank_details",models.TextField(blank=True)),("invoice_prefix",models.CharField(default="INV",max_length=10)),("default_tax_rate",models.DecimalField(decimal_places=2,default=12,max_digits=5)),("default_dpp_factor",models.DecimalField(decimal_places=6,default=0.916667,max_digits=8)),("created_at",models.DateTimeField(auto_now_add=True))]),
        migrations.CreateModel(name="Customer",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("name",models.CharField(max_length=200)),("email",models.EmailField(blank=True,max_length=254)),("phone",models.CharField(blank=True,max_length=40)),("npwp",models.CharField(blank=True,max_length=40)),("address",models.TextField(blank=True)),("notes",models.TextField(blank=True)),("created_at",models.DateTimeField(auto_now_add=True)),("company",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to="core.company"))]),
        migrations.CreateModel(name="Product",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("name",models.CharField(max_length=200)),("sku",models.CharField(blank=True,max_length=60)),("unit",models.CharField(default="pcs",max_length=30)),("price",models.DecimalField(decimal_places=2,default=0,max_digits=18)),("active",models.BooleanField(default=True)),("company",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to="core.company"))]),
        migrations.CreateModel(name="Invoice",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("number",models.CharField(max_length=40)),("issue_date",models.DateField()),("due_date",models.DateField()),("status",models.CharField(choices=[("draft","Draft"),("sent","Sent"),("partial","Partial"),("paid","Paid"),("overdue","Overdue"),("void","Void")],default="draft",max_length=12)),("tax_rate",models.DecimalField(decimal_places=2,default=12,max_digits=5)),("dpp_factor",models.DecimalField(decimal_places=6,default=0.916667,max_digits=8)),("discount",models.DecimalField(decimal_places=2,default=0,max_digits=18)),("notes",models.TextField(blank=True)),("created_at",models.DateTimeField(auto_now_add=True)),("company",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to="core.company")),("created_by",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to=settings.AUTH_USER_MODEL)),("customer",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="invoices",to="core.customer"))],options={"ordering":["-issue_date","-id"]}),
        migrations.CreateModel(name="InvoiceItem",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("description",models.CharField(max_length=250)),("quantity",models.DecimalField(decimal_places=2,default=1,max_digits=12)),("unit_price",models.DecimalField(decimal_places=2,max_digits=18)),("invoice",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="items",to="core.invoice"))]),
        migrations.CreateModel(name="Payment",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("date",models.DateField()),("amount",models.DecimalField(decimal_places=2,max_digits=18)),("method",models.CharField(blank=True,max_length=40)),("reference",models.CharField(blank=True,max_length=100)),("created_at",models.DateTimeField(auto_now_add=True)),("company",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to="core.company")),("invoice",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="payments",to="core.invoice"))]),
        migrations.CreateModel(name="Membership",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("role",models.CharField(choices=[("owner","Owner"),("admin","Admin"),("finance","Finance"),("sales","Sales"),("viewer","Viewer")],default="viewer",max_length=12)),("active",models.BooleanField(default=True)),("company",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="memberships",to="core.company")),("user",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="memberships",to=settings.AUTH_USER_MODEL))]),
        migrations.AddConstraint(model_name="invoice",constraint=models.UniqueConstraint(fields=("company","number"),name="unique_company_invoice_number")),migrations.AddConstraint(model_name="membership",constraint=models.UniqueConstraint(fields=("user","company"),name="unique_company_member"))]
